services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdash
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=s3,sqs,ses
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
volumes:
  pgdata: {}
